### ISSUE TITLE
x509 error trying to `helm repo add` this chart

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-migration#4]
```
helm repo add workflow-migration https://charts.deis.com/workflow-migration
Error: Get https://charts.deis.com/workflow-migration/index.yaml: x509: certificate signed by unknown authority
```

**Comment by mboersma** [comment]
I reported this based on a bug report from the #community channel. However it works for me with `helm` v2.1.0:
```
$ helm repo add workflow-migration https://charts.deis.com/workflow-migration
"workflow-migration" has been added to your repositories
$ helm version
Client: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
```

**Comment by mboersma** [comment]
This could be an issue with the `helm` v2.1.0 packaged for homebrew. The direct download from the README seems to Work For Me&trade;.

*Update*: no, the OP seems to have had the same problem using the direct download of helm v2.1.2.

**Comment by bacongobbler** [comment]
Is this on macOS? Could be the same issue as https://github.com/deis/workflow-cli/issues/271 if helm isn't compiled with at least Go v1.7.4.

**Comment by bacongobbler** [comment]
For clarity:

> Go's standard library crypto/tls provides a common mechanism for configuring TLS connections in tls.Config. The RootCAs field on this struct is a pool of certificates for the client to use as a trust store when verifying server certificates.

> This library contains utility functions for loading certificates destined for that field, as well as one other important thing:

> When the RootCAs field is nil, the standard library attempts to load the host's root CA set. This behavior is OS-specific, and the Darwin implementation contains [a bug that prevents trusted certificates from the System and Login keychains from being loaded](https://github.com/golang/go/issues/14514).

**Comment by mboersma** [comment]
`helm` v2.1.3 was built with go 1.7.4, so assuming this was on MacOS, it should be resolved. This originated from a conversation on Slack, so I'm going to close it since there's no OP to follow up on it.
